# Generated by Django 4.2.5 on 2023-12-13 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_mlmodel_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
